### ISSUE TITLE
bosh-release failing on 1.6

### ISSUE THREAD

**Issue by cholick** [cf-platform-eng/tile-generator#100]
On ops manager 1.6, we're unable to install a tile with a job type of bosh-release

```
RuntimeError
missing property "vm_credentials"
/home/tempest-web/tempest/web/app/models/persistence/models/job.rb:115:in `block in property_value'
...
```

https://docs.pivotal.io/partners/product-template-reference.html
"Ops Manager 1.7 does not require product authors to provide vm_credentials in
the property_blueprints for each job_type. vm_credentials are generated
automatically, and you can find them in the release manifest."

So we think we need to figure out how to use "vm_credentials" as they are
required for a PCF version older than 1.7

It looks like `metadata.yml` doesn't include the required block:

```
  property_blueprints:
  - name: vm_credentials
    type: salted_credentials
    default:
      identity: vcap
```

when the package type is `bosh-release`
