### ISSUE TITLE
Automatically pass environment variables to docker-bosh packages

### ISSUE THREAD

**Issue by guidowb** [cf-platform-eng/tile-generator#12]
The default forms for each app seem great for debugging and development, but many of those options probably should not be given to actual end-users of the production tile. We need a way to turn these on for development, and migrate only the required ones to custom forms for production.

**Comment by mdcarlson** [comment]
Thanks @guidowb for the great work on this utility!

I created a simple tile based on a Docker image.  The application in that image needs four environment variables.  I created form fields that successfully prompt for the needed attributes.  Can you clarify how those get passed to the app's environment?

M

**Comment by sparameswaran** [comment]
Add them under env-vars section of the manifest:

```
- name: docker-bosh1
  type: docker-bosh
  image_name: ubuntu # Needs to match `image` specified in manifest
  files:
  - path: resources/ubuntu_image.tgz
  cpu: 5
  memory: 4096
  ephemeral_disk: 4096
  persistent_disk: 2048
  instances: 1
  manifest: |
    containers:
    - name: test-ubuntu-docker
      image: ubuntu # should match the docker image name
      ..........
      env-vars:
      - test-key1: testValue1
      - test-key2: testValue2
      # Must add custom properties below   
      - custom-variable-name: (( .properties.customer_name.value ))
      - custom-variable-city: (( .properties.city.value ))
```
