### ISSUE TITLE
Support labels in dynamic service plans

### ISSUE THREAD

**Issue by mboldt** [cf-platform-eng/tile-generator#126]
E.g., if tile.yml includes:

```
dynamic_service_plans:
- name: display_name
  label: Display Name
  type: string
  description: "Display name"
  configurable: true
  ......
```

tile-generator should use that label in the property blueprints.
