### ISSUE TITLE
Can't configure canary_watch_time from tile.yml

### ISSUE THREAD

**Issue by pega-roska** [cf-platform-eng/tile-generator#157]
Right now there doesn't seem to be a good way to set custom values for canary_watch_time or update_watch_time from the tile.yml file.  What we'd like to be able to do is allow the end user of the tile to specify a custom maximum bound on the amount of time bosh will wait for the system to come up, in order to facilitate running in more resource constrained environments.

**Comment by guidowb** [comment]
Version 3.0.2 allows all update parameters to be overridden by specifying them in tile.yml. Will verify that they can also be included in forms before closing this issue.

**Comment by guidowb** [comment]
This works with 3.0.2:

```
forms:
- name: update_form
  label: Update Settings
  description: Example of user-configured update Settings
  properties:
  - name: canary_watch_timeout
    type: integer
    label: Canary Watch Timeout
    description: Maximum amount of time to allow canaries to take before going healthy
  - name: update_watch_timeout
    type: integer
    label: Update Watch Timeout
    description: Maximum amount of time to allow non-canaries to take before going healthy

update:
  canary_watch_time: 10000-(( .properties.canary_watch_timeout ))
  update_watch_time: 10000-(( .properties.update_watch_timeout ))
```
