### ISSUE TITLE
Add bosh links to docs and sample tile

### ISSUE THREAD

**Issue by mboldt** [cf-platform-eng/tile-generator#158]
Added support in f53bb3158dd4bd4554696ebd124af44b94789812

Use them like:

```yaml
 packages:
- name: tg-bosh-link
  # ...
  jobs:
  - name: provider
    templates:
    - name: provider
      release: echo_release
      provides: |
        other_guy_out:
          as: other_guy
    properties:
      foo: bar
  - name: echo_job
    templates:
    - name: echo_job
      release: echo_release
      consumes: |
        other_guy_in:
          from: other_guy
```
