### ISSUE TITLE
Secret property in a collection behaves not the same as at the top-level

### ISSUE THREAD

**Issue by zhongyi-zhang** [cf-platform-eng/tile-generator#165]
There are two secret property in my tile yml file, one at the top-level, another in a collection.

```
  - name: azure_broker_database_password
    type: secret
    label: Database Password
```

```
  - name: azure_sqldb_sql_server_pool
    type: collection
    configurable: true
    property_blueprints:
      - name: sqlServerName
        type: string
        label: SQL Server Name
      - name: administratorLogin
        type: string
        label: SQL Server Administrator Login
      - name: administratorLoginPassword
        type: secret
        label: SQL Server Administrator Login Password
    label: Sql Server Pool
```

But they are different formats when these two secrets are passed to environment variables:
Got azure_broker_database_password like
```
AZURE_BROKER_DATABASE_PASSWORD: fake-password
```
And got administratorLoginPassword like
```
AZURE_SQLDB_SQL_SERVER_POOL: [{"guid":"17f12937-b89e-496d-a32e-6e904e9b008c","sqlServerName":"fake-sql","administratorLogin":"fake-sql","administratorLoginPassword":{"secret":"fake-sql"}}]
```

I think the hash {"secret":"fake-sql"} may confuse users.
