### ISSUE TITLE
tile-generator won't allow 0 for default instances count

### ISSUE THREAD

**Issue by pega-roska** [cf-platform-eng/tile-generator#169]
When I set the default number of instances for bosh jobs, values greater than 0 are accepted, but 0 ends up getting turned into 1 by tile-generator.  

Sample yml to show which value I'm talking about:
```yml
packages:
 - name: sample-name
   type: bosh-release
   path: sample/path
   jobs:
   - instances: 0 # This becomes 1 in the built tile
     name: sample
```
