### ISSUE TITLE
Unable to add custom named_manifests snippet to tile

### ISSUE THREAD

**Issue by Infra-Red** [cf-platform-eng/tile-generator#190]
Hi, I'm trying to add custom named_manifests snippet to tile metadata file, but when I run `tile build` my snippet get replaced by autogenerated snippet, looks like it happens here https://github.com/cf-platform-eng/tile-generator/blob/aeac43a2ba8a7625a6f37ff9c5688679638ce527/tile_generator/template.py#L50
Is there any way to add custom manifest snippet to my tile.yml?

**Comment by mboldt** [comment]
@Infra-Red Could you explain your use case a bit here? The generated named manifest should have all the properties from the selector. Do you need something more in there?

**Comment by Infra-Red** [comment]
@mboldt You right, i need to pass additional properties in named manifest, for example I have radio button with three options Disable, AWS, Openstack and in each case i need to provide additional property in manifest: `provider: aws`, `provider: openstack` or leave provider blank if select Disable. So it's not enough for me to have only properties from autogenerated named manifest.

**Comment by Infra-Red** [comment]
@mboldt WDYT?

**Comment by mboldt** [comment]
I see two options here:
1. You can use the `value` of the selector to determine which choice was selected, and use that instead of a separate `provider` property.
2. You can set add a non-configurable property to each option_template with the provider name, something like:
```
forms:
- name: provider_form
  properties:
  - name: provider
    type: selector
    option_templates:
    - name: aws
      property_blueprints:
      - name: provider
        type: string
        configurable: false
        default: aws
```
