### ISSUE TITLE
Yo Dawg, I Heard you Like Templates

### ISSUE THREAD

**Issue by cholick** [cf-platform-eng/tile-generator#199]
Currently, when deploying a package of type app, the manifest as defined in `tile.yml` _does not_ go through Ops Managers templating substitution. This prevents form fields from controlling manifest values.

Use case: the deployed app's number of instances needs to be scaled out depending on the foundation's size (a nozzle, for example)

**Comment by cholick** [comment]
Workaround:
```
---
name: tile-gen-environment-check
icon_file: icon.png
label: Test tile
description: Cholick test tile

packages:
- name: tile-test-app-cholick
  type: app
  manifest:
    instances: MY_INSTANCE_COUNT
    path: app.zip
    buildpack: python_buildpack
    command: python app.py
    memory: 256M
  pre_deploy: |
    sed -i "s/MY_INSTANCE_COUNT/$SCALE_OUT/g" $PACKAGE_PATH/tile_test_app_cholick/manifest.yml


forms:
- name: test-config
  label: Test Config
  properties:
  - name: sample_property
    type: string
    label: Sample property
    description: Sample property to validate incoming app environment
  - name: scale_out
    type: integer
    label: Instances to run
    description: Always run 2
    default: 2
```
