### ISSUE TITLE
Errand rules incorrectly passed to final metadata tile manifest

### ISSUE THREAD

**Issue by Infra-Red** [cf-platform-eng/tile-generator#205]
Currently tile-generator not properly passes errand rules to the final tile metadata manifest.
https://github.com/cf-platform-eng/tile-generator/blob/155ffa37592e0d6968a5a1fc6eecff0c19a94747/tile_generator/templates/tile/metadata.yml#L612-L614

https://github.com/cf-platform-eng/tile-generator/blob/155ffa37592e0d6968a5a1fc6eecff0c19a94747/tile_generator/templates/tile/metadata.yml#L624-L626

`run_post_deploy_errand_default ` and `run_pre_delete_errand_default` should be specified inside errand job properties, here the example from `elastic-runtime` metadata template:
```
- name: mysql-rejoin-unsafe
  resource_label: MySQL Rejoin Unsafe Errand
  description: MySQL Rejoin Unsafe Errand
  manifest: |
    cf_mysql:
      mysql:
        galera_healthcheck:
          endpoint_username: (( .mysql.mysql_bootstrap_credentials.identity ))
          endpoint_password: (( .mysql.mysql_bootstrap_credentials.password ))
  static_ip: 0
  dynamic_ip: 1
  max_in_flight: 1
  single_az_only: false
  errand: true
  run_pre_delete_errand_default: true
  run_post_deploy_errand_default: when-changed
```
`pre_delete_errands ` and `post_deploy_errands` keys should contain only list of errands to run after a deploy or before deleting the deployment.
