### ISSUE TITLE
Property descriptions cannot contain colons

### ISSUE THREAD

**Issue by mboldt** [cf-platform-eng/tile-generator#210]
Due to the templating of the job spec file:

https://github.com/cf-platform-eng/tile-generator/blob/d9242c1dcf4e08f2a7f25bbc2b7576289db5c448/tile_generator/templates/jobs/spec#L57

a property description with colons, like:

```
forms:
- name: manifest-form-1
  properties:
  - name: my_string
    type: string
    label: My String
    description: "String like: foo"
```

end up inserting a YAML map (i.e., `{"description: {"String like": "foo"}}` in the job spec file, causing `bosh create release` to fail.

Our current refactoring efforts (from templating to generative approach) would fix this, as a straight YAML dump of a spec file object would properly quote the strings in the YAML.
