### ISSUE TITLE
Support BOSH link disambiguation

### ISSUE THREAD

**Issue by mboldt** [cf-platform-eng/tile-generator#219]
We have a use case where a service deploys multiple instances of the same BOSH job template, each providing a link for its service type, e.g.,:
```
instance_groups:
- name: small
  jobs:
  - name: small_job
    provides:
      svc: {as: svc_small}
  ...
- name: large
  jobs:
  - name: large_job
    provides:
      svc: {as: svc_large}
  ...
```
We need the `app-broker` in this tile/deployment to be able to get the host name for each instance of this service via the `*_HOST` and `*_HOSTS` environment variables. So, we need to generate the appropriate spec file, deployment manifest, and consumer in the deploy-all job template to support this.
