### ISSUE TITLE
consumes block output bug

### ISSUE THREAD

**Issue by cholick** [cf-platform-eng/tile-generator#231]
Single line consumes block syntax interacts incorrectly with how we're templating.

Sample input:
```yaml
  - name: route_registrar
    release: routing
    consumes: 'nats: {from: nats, deployment: (( ..cf.deployment_name ))}'
```
Expected metadata output:
```yaml
  - name: route_registrar
    release: routing
    consumes: 'nats: {from: nats, deployment: (( ..cf.deployment_name ))}'
```
Actual metadata output:
```yaml
  - name: route_registrar
    release: routing
    consumes: |
      'nats: {from: nats, deployment: (( ..cf.deployment_name ))}'
```

This doesn't work correctly when uploaded to OpsMan. Given the consumes block needs to be a literal string, it's much easier to provide correctly parsing input using the single line syntax & not deal with yaml's indentation issues.
