### ISSUE TITLE
From isn't required for intra-deployment BOSH links

### ISSUE THREAD

**Issue by cholick** [cf-platform-eng/tile-generator#247]
a `tile build` fails when the `from` block isn't specified in a BOSH link. From isn't a required field, links do quite a bit of matching and only need `from` is some cases

**Comment by cholick** [comment]
Going to have to work a bit more to build a concrete example, but, this manifest, for example:
```
- name: spacebears-link-broker
  type: app-broker
  enable_global_access_to_plans: true
  consumes:
    spacebears:
      type: baz

```
Results in
```
  - consumes: |
      spacebears: {}
```
the type field is stripped out

Using consumes block in a BOSH release seems to strip out the block entirely.
