### ISSUE TITLE
Breaking `_` vs `-` change in tile generator 12.0.5 vs 12.0.4 for broker name

### ISSUE THREAD

**Issue by cholick** [cf-platform-eng/tile-generator#272]
```
packages:
- name: my-broker
  type: app-broker
  manifest:
    path: resources/app.jar
    buildpack: java_buildpack_offline
```

In version 12.0.5, `deploy-all.sh.erb` has this line:
```
export BROKER_NAME=my_broker
```

In version 12.0.4, `deploy-all.sh.erb` has this line:
```
export BROKER_NAME=my-broker
```

I don't see a migration or a rename broker in the mix, and the code to find an existing broker isn't robust to this change, grepping for the exact string. This looks like a breaking change for existing installations.

* https://github.com/cf-platform-eng/tile-generator/releases/tag/v12.0.5
* https://github.com/cf-platform-eng/tile-generator/releases/tag/v12.0.4
