### ISSUE TITLE
- to _ Bug in Form Properties

### ISSUE THREAD

**Issue by cholick** [cf-platform-eng/tile-generator#275]
This tile input:
```
---
name: my-buildpack
icon_file: resoureces/me.jpg
label: My Buildpack
description: My slick buildpack

packages:
- name: my-buildpack-package
  type: buildpack
  path: resoureces/my-buildpack.zip
  buildpack_order: 99
```

Results in metadata containing:
```
property_blueprints:
- configurable: true
  default: my-buildpack-org
  name: org
  type: string
- configurable: true
  default: my-buildpack-space
  name: space
  type: string
- configurable: true
  default: false
  name: apply_open_security_group
  type: boolean
- configurable: true
  default: false
  name: allow_paid_service_plans
  type: boolean
- configurable: true
  default: 99
  name: my_buildpack_package_buildpack_order
  type: integer


form_types: 
- description: Configurable settings for buildpacks
  label: Buildpack Settings
  name: buildpacks
  property_inputs:
  - description: Enter order for the my-buildpack-package buildpack
    label: my-buildpack-package Buildpack Order
    reference: .properties.my-buildpack-package_buildpack_order
```

Note the property blueprint name `my_buildpack_package_buildpack_order` doesn't match the reference in the form `.properties.my-buildpack-package_buildpack_order`
