### ISSUE TITLE
Issues with YAML transforming datetime to seconds

### ISSUE THREAD

**Issue by mmanciop** [cf-platform-eng/tile-generator#308]
The following snipped leads to the default value showing up as `16200` (amount of seconds in '04:30') in Ops Manager:

```yml
      - name: time
        type: string
        label: Update time
        description: "Time of day when the update is executed (hh:mm format, in UTC)."
        default: '04:30'
```

Since tile generator strips the surrounding `'`, `"` or even type casts like `!!str`, there is nothing preventing [YAML from converting `04:30` to `16200`](https://stackoverflow.com/questions/2286587/how-to-keep-strings-in-yaml-from-getting-converted-to-times).
