### ISSUE TITLE
Specifying a single binary for an app does not work

### ISSUE THREAD

**Issue by guidowb** [cf-platform-eng/tile-generator#95]
```
packages:
- name: foo
 type: app-broker
 manifest:
   path: builds/foo
   command: foo
   memory: 512M
   buildpack: binary-buildpack
```

results in messages saying `No app files found in /var/vcap/packages/foo/foo`
